### ISSUE TITLE
lyric tag doesn't work

### ISSUE THREAD

**Issue by SADEGH-H** [eidoriantan/mp3tag.js#10]
Hi,
in this address:
https://mp3tag.js.org/editor/
I've added mp3 file and add this in lyrics section:
eng|lyrics
then I click on the Save button.
then this error has been shown:
 Writing Error
ID3v2 Error: Frame validation failed "ID: USLT, Message: ID3v2 Error: Frame validation failed "Language/descriptor/text is not a string""
Please tell me how can I add value to the lyrics section.
Thanks

**Comment by eidoriantan** [comment]
The '|' character separates the language, descriptor, and the actual lyrics. So, it should be `eng||lyrics` (Note the two '|'). The language will be `eng`, descriptor is ` ` (blank) and the lyrics is `lyrics`.
