### ISSUE TITLE
Cover for song

### ISSUE THREAD

**Issue by ivioninjs** [eidoriantan/mp3tag.js#256]
Hello!
thanks for the work you've done!
It's awesome tool! 

But, I didn`t understand how add image (png | jpg ) to song.
Could you write simple example please? 

Thanks advanced!

**Comment by eidoriantan** [comment]
Hi! You can add the cover image to songs by modifying the APIC tag.
```javascript
mp3tag.tags.v2.APIC = [{
  format: 'image/jpeg', // or image/png
  type: 3,
  description: '',
  data: bytes
}]
```

You can see the full list of types [here](https://id3.org/id3v2.3.0#line-1-48). For the bytes' value, you have to read the image's buffer first then convert it to `Uint8Array`:
```javascript
const bytes = new Uint8Array(buffer)
```

**Comment by ivioninjs** [comment]
Thanks a lot!

**Comment by peshoFT** [comment]
"mp3tag.tags.save is not a function" 
I directly copied the example that you presented

**Comment by eidoriantan** [comment]
> "mp3tag.tags.save is not a function"
> I directly copied the example that you presented

Hey, you should use `mp3tag.save()` instead of `mp3tag.tags.save()`

**Comment by peshoFT** [comment]
> > "mp3tag.tags.save is not a function"
> > I directly copied the example that you presented
> 
> Hey, you should use `mp3tag.save()` instead of `mp3tag.tags.save()`

Certainly going to try as soon as I get home, thank you in advance

**Comment by peshoFT** [comment]
Alright the .save works now 
Next question: how do I apply the tags to a given file?

**Comment by eidoriantan** [comment]
> Alright the .save works now
> Next question: how do I apply the tags to a given file?

Saving it modifies the buffer at `mp3tag.buffer` so you can use this for download.

If you are using browser, you can download the file by:
```javascript
const fileBlob = new Blob([mp3tag.buffer], { type: 'audio/mpeg' })
const a = document.createElement('a')
document.body.appendChild(a)
const url = window.URL.createObjectURL(fileBlob)
a.href = url
a.download = 'filename.mp3'
a.click()
```

And if you're using Node, you can use it to save the file by:
```javascript
const fs = require('fs')
fs.writeFileSync('filename.mp3', mp3tag.buffer)
```
