### ISSUE TITLE
[RVAD/WFED/TGID] Frame

### ISSUE THREAD

**Issue by himbolion** [eidoriantan/mp3tag.js#416]
**Frame links**
You can find mentions of **WFED** and **TGID** on [the apple forums](https://discussions.apple.com/thread/1107361) though it seems to only be a string with a URL

**RVAD** seems to be "Relative volume adjustment" and, if I'm reading [this](https://en.wikipedia.org/wiki/ID3#ID3v2_frame_specification) correctly is the same as RVA2?

**Comment by eidoriantan** [comment]
**WFED** and **TGID** are not standard tags and it wasn't documented anywhere. However, I'll try to research more about this and implement it.

As for the **RVAD/RVA2** tags, they're not currently supported yet.

I'll work on these details as soon as I'm available

**Comment by himbolion** [comment]
Yeah it took me a while to find anything about WFED and TGID, to actually "somewhat" know what they are

That'd be amazing! I'm currently using this libary within Deno to sort my Music Library based on it's MetaData and it works really well!

**Comment by eidoriantan** [comment]
I already released a new version of the library with these frames

**Comment by himbolion** [comment]
bless, tysm
