### ISSUE TITLE
[BUG] SYLT validator don't work

### ISSUE THREAD

**Issue by ccanasj** [eidoriantan/mp3tag.js#502]
Hi!
Thanks for this amazing tool!

I want to add SYLT tag but in strict mode throw the error
`Error: Lyrics must follow this format: [mm:ss.xxx] at SYLT`

and this is the synced lyrics:

**_[00:52.614] Tequila!
[01:35.328] Tequila!
[02:06.259] Tequila!_**

I think is because the regex `const syltRegex = /^((\[\d{1,}:\d{2}\.\d{3}\]) ?(.*)|)/` has `|` at the end

```
if (sylt.lyrics.split('\n').every(entry => syltRegex.test(entry))) {
    throw new Error('Lyrics must follow this format: [mm:ss.xxx]')
}
```
and negate that `if` because always enter when the format is correct

Thanks in advance!

**Comment by eidoriantan** [comment]
Thank you for noticing this bug.

I already updated the RegExp for SYLT frame and will publish a new version of the library.
