### ISSUE TITLE
Saving/Writing just doesn't work for me

### ISSUE THREAD

**Issue by JohnThomasMilan** [eidoriantan/mp3tag.js#575]
Using the example code I am able to read in and edit the tags from a file. I can even use mp3tag.save() and then read again and my changes show up in console. However when I go look at the actual mp3 file in the folder nothing has changed. I have even used fs.writeFileSync to write the edited buffer to a new mp3 file and it is identical to the original as well. Not sure what I'm doing wrong.

My code:
```
var filepath = `./data/Dream Fiend/Outland/Dreams.mp3`;
const buffer = fs.readFileSync(filepath);
const verbose = true;
const mp3tag = new MP3tag(buffer, verbose);
mp3tag.read();
mp3tag.tags.artist = "TEST";
mp3tag.tags.title = "TEST";
mp3tag.save( {
    strict: true,
    id3v2: { padding: 4096 }
});
mp3tag.read();
console.log(mp3tag.tags);
```

Output shows:
```
ID3v2 found, reading...
ID3v2 reading finished
Validating ID3v2...
Writing ID3v2...
ID3v2 found, reading...
ID3v2 reading finished
{
  v2: {
    TPOS: '1',
    TALB: 'Outland',
    TRCK: '4',
    TSSE: 'Lavf59.23.100',
    TIT2: 'TEST',
    TPE1: 'TEST'
  },
  v2Details: {
    version: [ 4, 0 ],
    flags: {
      unsynchronisation: false,
      extendedHeader: false,
      experimentalIndicator: false,
      footerPresent: false
    },
    size: 102
  }
}
```
file after running my code:
![image](https://github.com/eidoriantan/mp3tag.js/assets/52258941/1d9ddf2a-c6a3-441c-b4d8-2ec0b339a9a3)

**Comment by eidoriantan** [comment]
Hello,

The code you've shown doesn't have `fs.writeFileSync`. You must save the tags first then write the new saved buffer to the file.

**Comment by djcee-b** [comment]
@JohnThomasMilan do you mind sharing your code with bathe writefilesync in as I am facing the same issue with not seeing the changes in the actual mp3. 

Thanks
