### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by djcee-b** [eidoriantan/mp3tag.js#610]
Can we please get some updated examples please. Some with the write filesync method

Thanks

**Comment by eidoriantan** [comment]
Hello,

The library doesn't directly modify the file since it has to support browsers as well. You'll have to manually read and write the buffer to the file if you're using Nodejs.

I already updated the example codes on how to use the library with Node's `writeFileSync` method

**Comment by djcee-b** [comment]
Thanks, I have used this example but I am still facing an error:
First of all: 

mp3tag.tags.save()
            ^
TypeError: mp3tag.tags.save is not a function

Then upon changing this to mp3tag.save() When i writeFileSync i get:

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of ArrayBuffer

Could you please assist with this. I will also create a proper issue around this
