### ISSUE TITLE
Option To Update Specific Tags and Not Update/Create Any Others

### ISSUE THREAD

**Issue by djcee-b** [eidoriantan/mp3tag.js#614]
I am creating a project where I am updating MP3 ID3v2 tags,
I only want to update the year and genre but upon saving it is create a new batch of GEOB tags.

BEFORE saving: 	    
GEOB: [	
      [Object], [Object],	
      [Object], [Object],	
      [Object], [Object],	
      [Object], [Object]
      
AFTER saving:
GEOB: [
  [Object], [Object],
  [Object], [Object],
  [Object], [Object],
  [Object], [Object],
  [Object], [Object],
  [Object], [Object],
  [Object], [Object],
  [Object]
],

Is there any way to only update certain tags and not touch the GEOB?

This is the code:

```javascript
    if (fileSizeInMB < 30) {
          const buffer = fs.readFileSync(filepath)
          const mp3tag = new MP3Tag(buffer, true)

          const beforeTags = mp3tag.read()

          if (mp3tag.tags.v2==null) {
            mp3tag.save({
              strict: false, // Use strict mode when validating
              id3v1: { include: false }, // Add ID3v1 tags to buffer
              id3v2: {
                include: true, // Add ID3v2 tags to buffer
                unsynch: false, // Use unsynchronisation scheme
                version: 4, // ID3v2 major version
                padding: 2048 // Number of null bytes added after ID3v2 tag
              }
            })
            const noV2nodeBuffer = Buffer.from(mp3tag.buffer)
            fs.writeFileSync(filepath, noV2nodeBuffer)
            const beforeTags2 = mp3tag.read()
          }

          mp3tag.tags.v2.TCON = 'No Genre'
          mp3tag.tags.v2.TCOM = 'No Data'
          mp3tag.tags.v2.TDRC = '0000'
          mp3tag.tags.v2.TYER = '0000'



          mp3tag.save({
            strict: false, // Use strict mode when validating
            id3v1: { include: false }, // Add ID3v1 tags to buffer
            id3v2: {
              include: true, // Add ID3v2 tags to buffer
              unsynch: false, // Use unsynchronisation scheme
              version: 3, // ID3v2 major version
              padding: 4096 // Number of null bytes added after ID3v2 tag
            }
          })

          if (mp3tag.error !== '') throw new Error(mp3tag.error)

          fs.writeFileSync(filepath, mp3tag.buffer)

          const afterTags = mp3tag.read()
          console.log(afterTags)

        } else {
          console.log("File Size is Too Big at "+fileSizeInMB+" MB")
        }
```

Thanks

**Comment by eidoriantan** [comment]
Hello,

I apologize for the late response, but would you be able to attach the audio file with the GEOB metadata? I'm unable to debug and recreate this issue

**Comment by djcee-b** [comment]
[BROKEN.zip](https://github.com/eidoriantan/mp3tag.js/files/12594359/BROKEN.zip)
Also, these two tracks when you update the tags it removes the first second of the mp3

**Comment by eidoriantan** [comment]
> [FILES.zip](https://github.com/eidoriantan/mp3tag.js/files/12584467/FILES.zip)
> 
> Hi Here are the two attached files. I am using a software called Serato DJ Pro, When i update the metatags it corrupts the MP3 because of a change in the GEOB tags

I had just tested these files and updating tags other than GEOB doesn't affect the original GEOB tag and only affects the tags you wanted to update.

Also, from your original code, don't `save()` before `read()` as that will remove all tags from the audio.

Here's the code I used for testing:

```javascript

const fs = require('node:fs')
const MP3Tag = require('../dist/mp3tag')

const buffer = fs.readFileSync('YG - Toxic (Dirty).mp3')
const mp3tag = new MP3Tag(buffer, true)

const tags = mp3tag.read()
console.log('Before tags', tags)

mp3tag.tags.v2.TCON = 'No genre'
mp3tag.tags.v2.TCOM = 'No Data'
mp3tag.tags.v2.TDRC = '0000'
mp3tag.tags.v2.TYER = '0000'

mp3tag.save({
  strict: false, // Use strict mode when validating
  id3v1: { include: false }, // Add ID3v1 tags to buffer
  id3v2: {
    include: true, // Add ID3v2 tags to buffer
    unsynch: false, // Use unsynchronisation scheme
    version: 3, // ID3v2 major version
    padding: 4096 // Number of null bytes added after ID3v2 tag
  }
})

if (mp3tag.error !== '') throw new Error(mp3tag.error)
console.log('After tags', mp3tag.tags)
```

**Comment by eidoriantan** [comment]
> [BROKEN.zip](https://github.com/eidoriantan/mp3tag.js/files/12594359/BROKEN.zip) Also, these two tracks when you update the tags it removes the first second of the mp3

Regarding this issue, I already opened a new issue and pushed a fix commit.

**Comment by djcee-b** [comment]
> > [FILES.zip](https://github.com/eidoriantan/mp3tag.js/files/12584467/FILES.zip)
> > Hi Here are the two attached files. I am using a software called Serato DJ Pro, When i update the metatags it corrupts the MP3 because of a change in the GEOB tags
> 
> I had just tested these files and updating tags other than GEOB doesn't affect the original GEOB tag and only affects the tags you wanted to update.
> 
> Also, from your original code, don't `save()` before `read()` as that will remove all tags from the audio.
> 
> Here's the code I used for testing:
> 
> ```js
> const fs = require('node:fs')
> const MP3Tag = require('mp3tag.js')
> 
> const buffer = fs.readFileSync('YG - Toxic (Dirty).mp3')
> const mp3tag = new MP3Tag(buffer, true)
> 
> const tags = mp3tag.read()
> console.log('Before tags', tags)
> 
> mp3tag.tags.v2.TCON = 'No genre'
> mp3tag.tags.v2.TCOM = 'No Data'
> mp3tag.tags.v2.TDRC = '0000'
> mp3tag.tags.v2.TYER = '0000'
> 
> mp3tag.save({
>   strict: false, // Use strict mode when validating
>   id3v1: { include: false }, // Add ID3v1 tags to buffer
>   id3v2: {
>     include: true, // Add ID3v2 tags to buffer
>     unsynch: false, // Use unsynchronisation scheme
>     version: 3, // ID3v2 major version
>     padding: 4096 // Number of null bytes added after ID3v2 tag
>   }
> })
> 
> if (mp3tag.error !== '') throw new Error(mp3tag.error)
> console.log('After tags', mp3tag.tags)
> ```

I am only saving before read here just incase an mp3 DOESNT have id3v2 tags. That is okay isnt it?

**Comment by djcee-b** [comment]
Okay, do you need to push a new release out for me to get it in my nodejs project? 
As at the moment I am on 3.4.1 version

Thanks

**Comment by eidoriantan** [comment]
> > > [FILES.zip](https://github.com/eidoriantan/mp3tag.js/files/12584467/FILES.zip)
> > > Hi Here are the two attached files. I am using a software called Serato DJ Pro, When i update the metatags it corrupts the MP3 because of a change in the GEOB tags
> > 
> > 
> > I had just tested these files and updating tags other than GEOB doesn't affect the original GEOB tag and only affects the tags you wanted to update.
> > Also, from your original code, don't `save()` before `read()` as that will remove all tags from the audio.
> > Here's the code I used for testing:
> > ```js
> > const fs = require('node:fs')
> > const MP3Tag = require('mp3tag.js')
> > 
> > const buffer = fs.readFileSync('YG - Toxic (Dirty).mp3')
> > const mp3tag = new MP3Tag(buffer, true)
> > 
> > const tags = mp3tag.read()
> > console.log('Before tags', tags)
> > 
> > mp3tag.tags.v2.TCON = 'No genre'
> > mp3tag.tags.v2.TCOM = 'No Data'
> > mp3tag.tags.v2.TDRC = '0000'
> > mp3tag.tags.v2.TYER = '0000'
> > 
> > mp3tag.save({
> >   strict: false, // Use strict mode when validating
> >   id3v1: { include: false }, // Add ID3v1 tags to buffer
> >   id3v2: {
> >     include: true, // Add ID3v2 tags to buffer
> >     unsynch: false, // Use unsynchronisation scheme
> >     version: 3, // ID3v2 major version
> >     padding: 4096 // Number of null bytes added after ID3v2 tag
> >   }
> > })
> > 
> > if (mp3tag.error !== '') throw new Error(mp3tag.error)
> > console.log('After tags', mp3tag.tags)
> > ```
> 
> I am only saving before read here just incase an mp3 DOESNT have id3v2 tags. That is okay isnt it?

Yes, that is perfectly fine but just note that it will overwrite the old tags.
