### ISSUE TITLE
Need "Album Artist" tag

### ISSUE THREAD

**Issue by emanuelchristo** [eidoriantan/mp3tag.js#62]
Please add support for "album artist" tag also.

**Comment by eidoriantan** [comment]
The `TPE2` tag is used for album artist by many softwares such as [mp3tag](https://help.mp3tag.de/main_tags.html) and iTunes.
The tag is only supported by versions ID3v2.3 and ID3v2.4. You can read more about the tag `TPE2` [here](https://id3.org/id3v2.3.0#line-456).

**Comment by eidoriantan** [comment]
If you do not have any more further questions, please close this issue.

Thanks for giving an interest to the project!
