### ISSUE TITLE
[TSO2] Album Artist Sort

### ISSUE THREAD

**Issue by rsolorio** [eidoriantan/mp3tag.js#622]
It looks like there's already support for multiple sort frames like: title sort, album sort, artist sort, composer sort, etc

However, there's currently no support for the album artist sort frame [TSO2].

This might be a simple change since it follows the same format as the other sorts: a standard text frame.

**Comment by eidoriantan** [comment]
Hello, would you be able to provide any documentations about the TSO2 frame?

**Comment by rsolorio** [comment]
Hi,

From what I understand sorting fields (including TSO2) are not "official" standards (they are considered "de facto" standards) which makes it harder to find proper documentation; however, all sorting fields in your source code (TSOT, TSOP, TSOC, TSOA) have the same format, they are regular text frames, so TSO2 also falls into the same format.

What I can provide is references to other libraries implementing this frame if that's useful.

**Comment by eidoriantan** [comment]
This is now supported at version 3.7.0
