### ISSUE TITLE
[TPUB] Publisher

### ISSUE THREAD

**Issue by rsolorio** [eidoriantan/mp3tag.js#631]
I would like to request support for the publisher tag TPUB.

It is a regular text frame without any special format, supported for Id3v2.3 and Id3v2.4.

Here's a reference to the TagLibSharp library and how they implement the tag:
https://github.com/mono/taglib-sharp/blob/c853d26fcf831b9c7bf1b1bc7734c2a8690ca163/src/TaglibSharp/Id3v2/Frames/TextIdentificationFrame.cs

That file lists all the tags that are "regular text" frames, including the TPUB frame. It follows the same format as tags like TIT1, TIT2, TIT3, etc.

Here are some references although they don't provide clear information about the tag format:
https://docs.mp3tag.de/mapping/#publisher
https://exiftool.org/TagNames/ID3.html
https://mutagen-specs.readthedocs.io/en/latest/id3/id3v2.4.0-frames.html#tpub

**Comment by eidoriantan** [comment]
The tag `TPUB` is already supported.

https://github.com/eidoriantan/mp3tag.js/blob/4cff17644ca605914853bf40309088175ac09e51/src/id3v2/frames.mjs#L381C6-L381C6

**Comment by rsolorio** [comment]
You are right, it works. The reason why I requested it is because it is not listed in the official doc, and I assumed it wasn't there.
https://mp3tag.js.org/docs/frames.html

Thanks

**Comment by eidoriantan** [comment]
> You are right, it works. The reason why I requested it is because it is not listed in the official doc, and I assumed it wasn't there. https://mp3tag.js.org/docs/frames.html
> 
> Thanks

Oh didn't noticed that, will update the docs. Thank you for reporting it
