### ISSUE TITLE
[BUG] mp3tag.buffer always return corrupt buffer

### ISSUE THREAD

**Issue by 4rvx** [eidoriantan/mp3tag.js#632]
**Describe the bug**
mp3tag.buffer returns corrupt buffer

**Codes used**
```js
    const buffer = myBuffer // My working audio buffer

    const mp3tag = new MP3Tag(buffer, true);

    mp3tag.read();

    mp3tag.tags.title = "Title";
    mp3tag.tags.artist = "Artist";

    mp3tag.save({ strict: true });

    // Check for error
    if (mp3tag.error !== "") {
        console.log(mp3tag.error);
        throw new Error("Error"); // Which never runs because there IS no error
    }

    mp3tag.read();
    await fsPromise.writeFile("audio-original.mp3", buffer); // normal good audio
    await fsPromise.writeFile("audio.mp3", mp3tag.buffer); // corrupt audio
```

**Expected behavior**
I expect audio.mp3 file to be playable 💀

**Additional context**
I tried `JSON.parse()` for the buffer but that gives an error, which means it's a corrupt file? idk

**Comment by eidoriantan** [comment]
Would you be able to provide a sample audio so I could test this on my end?

**Comment by 4rvii** [comment]
@eidoriantan
Github only supports these attachments:
GIF, JPEG, JPG, MOV, MP4, PNG, SVG, WEBM, CPUPROFILE, CSV, DMP, DOCX, FODG, FODP, FODS, FODT, GZ, JSON, JSONC, LOG, MD, ODF, ODG, ODP, ODS, ODT, PATCH, PDF, PPTX, TGZ, TXT, XLS, XLSX or ZIP.

I use fent/ytdl-core download this as MP3: https://www.youtube.com/watch?v=srodNyimqTM

**Comment by eidoriantan** [comment]
Okay, will test this once I'm available

**Comment by 4rvii** [comment]
Also, Do it in buffer type not saved in file

**Comment by 4rvii** [comment]
any updates?

**Comment by 4rvii** [comment]
Realized the problem was with the file. For some reason it wasn't even editable in windows default properties section.
