### ISSUE TITLE
[BUG] Removing the Track tag

### ISSUE THREAD

**Issue by RedHeadEmile** [eidoriantan/mp3tag.js#635]
[The documentation](https://mp3tag.js.org/docs/frames.html) about track is:

> track
> Reads ID3v2 TRCK tag value first, ID3v1 track tag otherwise an empty string
> Type: string

But when I set the `track` to an empty string, I get `Invalid format (eg. 1/2) at TRCK`.

If I found the right place in the code ([here](https://github.com/eidoriantan/mp3tag.js/blob/main/src/id3v2/validate.mjs#L27)), it seems that "empty string" isn't checked at all. Maybe a specific behaviour should be implemented for that case ?

**Comment by eidoriantan** [comment]
Oh didn't notice that. Empty string stated in that documentation refers to values parsed from buffer.

In that case, `TRCK` tag should not be added when setting `track` to an empty string. Will work on this.

**Comment by eidoriantan** [comment]
> Another thing: when I set the track value to `9/12`, the file is well written but if I read it, I only get `9`, the `/12` part is gone.

Were you accessing the `track` property? That is intended so that it is compatible with ID3v1. You'll have to access directly the ID3v2's `TRCK` frame to read the whole part. Should be available at `mp3tag.tags.v2.TRCK`

**Comment by RedHeadEmile** [comment]
> > Another thing: when I set the track value to `9/12`, the file is well written but if I read it, I only get `9`, the `/12` part is gone.
> 
> Were you accessing the `track` property? That is intended so that it is compatible with ID3v1. You'll have to access directly the ID3v2's `TRCK` frame to read the whole part. Should be available at `mp3tag.tags.v2.TRCK`

Yes I was, I will fix it, thanks :)
