### ISSUE TITLE
[FEATURE] ID3v2.2

### ISSUE THREAD

**Issue by RedHeadEmile** [eidoriantan/mp3tag.js#636]
I don't know much about ID3 versions but would it be hard to support ID3v2.2 ?

I know extremly specific, but, as example, the soundtrack of the game "Portal" released in 2007 uses ID3V2.2 for their mp3 file. So I can't read the buffer from them as I get "Unknown ID3v2 major version".

**Comment by eidoriantan** [comment]
It wasn't supported because the official specifications of ID3v2.2 was not properly documented. I guess we can support this version following this [spec](https://mutagen-specs.readthedocs.io/en/latest/id3/id3v2.2.html)
