### ISSUE TITLE
editor codes

### ISSUE THREAD

**Issue by SADEGH-H** [eidoriantan/mp3tag.js#8]
Hi,
Will you please share the source of this page:
https://mp3tag.js.org/editor/
Thanks

**Comment by eidoriantan** [comment]
It's in the [gh-pages](https://github.com/eidoriantan/mp3tag.js/tree/gh-pages) branch.

**Comment by eidoriantan** [comment]
If you don't have any more questions, I'm closing this. Thank you for taking an interest on the project!

**Comment by SADEGH-H** [comment]
Thanks alot
